# Generated by Django 2.2.7 on 2019-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_goals', models.CharField(default='n/a', max_length=255)),
                ('hours_of_sleep', models.CharField(default='n/a', max_length=100)),
                ('bedtime', models.CharField(default='n/a', max_length=100)),
                ('routine', models.CharField(default='n/a', max_length=255)),
            ],
        ),
    ]
