# Generated by Django 2.2.7 on 2019-11-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthgoal',
            name='mental_health_goal',
            field=models.CharField(choices=[('reduce anxiety', 'reduce anxiety'), ('reduce depression', 'reduce depression'), ('increase self-esteem', 'increase self_esteem'), ('substance use', 'reduce and/or eliminate substance use')], default='n/a', max_length=255),
        ),
    ]
