# Generated by Django 2.2.7 on 2019-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0002_auto_20191126_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisegoal',
            name='daily_focus',
            field=models.CharField(choices=[('cardio', 'cardio'), ('build strength', 'build strength'), ('flexibility', 'flexibility'), ('balance', 'balance')], default='n/a', max_length=300),
        ),
        migrations.AddField(
            model_name='exercisegoal',
            name='hours_of_exercise',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='exercisegoal',
            name='workout_schedule',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercisegoal',
            name='body_goals',
            field=models.CharField(choices=[('weight loss', 'weight loss'), ('increase strength', 'increase strength'), ('improve endurance', 'improve endurance'), ('reduce health risks', 'reduce health risks'), ('energy boost', 'energy boost')], default='n/a', max_length=100),
        ),
    ]
