# Generated by Django 2.2.7 on 2019-11-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0002_exercisegoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(default='n/a', max_length=255)),
                ('meditation', models.CharField(default='n/a', max_length=255)),
            ],
        ),
    ]
