# Generated by Django 2.2.7 on 2019-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0003_mentalhealthgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_schedule', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('hours_of_exercise', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('daily_focus', models.CharField(choices=[('cardio', 'cardio'), ('strength building', 'strength building'), ('flexibility', 'flexibility'), ('balance', 'balance')], default='n/a', max_length=300)),
            ],
        ),
    ]
