# Generated by Django 2.2.7 on 2019-11-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0003_auto_20191126_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseSchedule',
        ),
    ]
