# Generated by Django 2.2.7 on 2019-11-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0004_delete_exerciseschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisegoal',
            old_name='hours_of_exercise',
            new_name='minutes_of_exercise',
        ),
    ]
