# Generated by Django 2.2.7 on 2019-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0004_exerciseschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination', models.CharField(default='n/a', max_length=500)),
            ],
        ),
    ]
