# Generated by Django 2.2.7 on 2019-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0005_auto_20191127_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisegoal',
            name='minutes_of_exercise',
            field=models.IntegerField(default=0),
        ),
    ]
