# Generated by Django 2.2.7 on 2019-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0006_auto_20191125_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthgoal',
            name='therapy',
            field=models.CharField(choices=[('twice a week', 'twice a week'), ('once a week', 'once_a_week'), ('every other week', 'every_other_week'), ('once a month', 'once a month')], default='n/a', max_length=500),
        ),
    ]
