# Generated by Django 2.2.7 on 2019-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0006_auto_20191127_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthgoal',
            name='medication',
            field=models.CharField(choices=[('does not apply to me', 'does not apply to me'), ('take in the morning', 'take in the morning'), ('take at night', 'take at night'), ('take in morning and night', 'take in the moring and night')], default='n/a', max_length=255),
        ),
    ]
