# Generated by Django 3.0 on 2019-12-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0007_auto_20191202_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisegoal',
            name='daily_focus',
            field=models.CharField(choices=[('cardio', 'cardio'), ('weight lifting', 'weight lifting'), ('yoga', 'yoga')], default='n/a', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentalhealthgoal',
            name='medication',
            field=models.CharField(choices=[('does not apply to me', 'does not apply to me'), ('take in the morning', 'take in the morning'), ('take at night', 'take at night'), ('take in morning and night', 'take in the morning and night')], default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='sleepgoal',
            name='sleep_goals',
            field=models.CharField(choices=[('sleep more', 'sleep more'), ('sleep less', 'sleep less')], default='n/a', max_length=255),
        ),
    ]
