# Generated by Django 2.2.7 on 2019-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0008_auto_20191125_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarygoal',
            name='dietary_goal',
            field=models.CharField(choices=[('lose weight', 'lose weight'), ('gain weight', 'gain weight'), ('improve health', 'improve health')], default='n/a', max_length=500),
        ),
    ]
