# Generated by Django 2.2.7 on 2019-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0009_dietarygoal_dietary_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseschedule',
            name='daily_focus',
            field=models.CharField(choices=[('cardio', 'cardio'), ('build strength', 'build strength'), ('flexibility', 'flexibility'), ('balance', 'balance')], default='n/a', max_length=300),
        ),
    ]
