# Generated by Django 2.2.7 on 2019-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0010_auto_20191125_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthgoal',
            name='mental_health_goal',
            field=models.CharField(choices=[('reduce anxiety', 'reduce anxiety'), ('reduce depression', 'reduce depression'), ('increase self-esteem', 'increase self_esteem'), ('substance use', 'reduce and/or reduce substance use')], default='n/a', max_length=255),
        ),
    ]
